### PR TITLE
mobile sizing fix

### PR DESCRIPTION
**Pull request by demanr**
Review and lmk if this is preferable. Only changed scaling for mobile to be a bit smaller

## Summary by CodeRabbit

- **Style**
	- Adjusted image scaling on the homepage for improved visual presentation across different screen sizes.

### CODE REVIEW

**Review by Krish120003 — CHANGES_REQUESTED** [review]
image

This doesn't look right, the dinos and logo are floating above the sand.

**Comment by demanr** [comment]
> image
> 
> This doesn't look right, the dinos and logo are floating above the sand.

What screen size was this on @Krish120003 ?

**Comment by Krish120003** [comment]
It's just on my phone

> What screen size was this on @Krish120003 ?

**Comment by err53** [comment]
@Krish120003 @demanr is this still broken?

**Pull request closed without merging**
